version: '3.4'

services:
  mssql-server:
    container_name: chatserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment :
      ACCEPT_EULA: "Y"
      MSSQL_son2002e_PASSWORD: "son2002e"
      MSSQL_PID: Developer
    ports:
     - "8002:1433"
  webapp:
    build: .
    image: chatserverapi
    ports:
     - "5000:80"
     - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=sonztz123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      -  DatabaseServer:"mssql-server"
      -  DatabasePort:"1443"
      -  DatabasePassword:"son2002e"
      -  DatabaseName:"ChatServerApi"
  
    volumes:
      - ~/.aspnet/https:/https:ro



  